### ISSUE TITLE
Embedded liquid-if within a liquid-wormhole does not render

### ISSUE THREAD

**Issue by svvitale** [pzuraq/liquid-wormhole#18]
I'm using liquid-wormhole to build modal dialogs (which it works GREAT for).  I've run into an issue where having a liquid-if embedded in a liquid-wormhole does not render.  It doesn't seem to matter if the conditional is true or false, it does not render at all.  Here's the relevant commit from an example Ember app:

https://github.com/svvitale/liquid-wormhole-embedded-liquid-if/commit/eddf36a7f02b372140c7b126ffedc193e03fa7fc

And an image of how it's being rendered:

![2016-10-26 09_39_12-liquidwormholetest](https://cloud.githubusercontent.com/assets/137162/19733147/692580a8-9b60-11e6-8f09-f2791f221bff.png)

The red box (the modal) should have some additional content indicating whether the liquid-if is true or not.  Neither branch of the liquid-if is displayed.

**Comment by spencer516** [comment]
I've also experienced this, though I found the issue through `liquid-tether` and trying to put a `liquid-outlet` inside of it. 

It seems that the issue is [this](https://github.com/pzuraq/liquid-wormhole/blob/master/addon/styles/addon.css#L11) CSS declaration which is being applied to _all_ `.liquid-child`s, rather than just the one it's intended to target. 

It might be a simple fix, and I'm happy to submit a PR — but, it's not clear what that selector intends to do. For my purposes, everything seems to work okay when I comment out that CSS block. ¯\_(ツ)_/¯

**Comment by pzuraq** [comment]
Ah, thanks for tracking it down! That makes sense. That selector removes some of the basic assumptions liquid-fire makes about `liquid-child`s because they don't apply in our case. Generally speaking, a `liquid-child` should contain it's content entirely and not allow it to overflow, because it is the animation container.

In our case, we're trying to animate a container the size of the viewport (generally, that's why this only applies to the default container, allowing others to customize it as they see fit). We also don't want our liquid-child to take up the size of the viewport because then nothing else would be clickable. This isn't an issue, because once we move things outside of the window we can't see it anymore (that's what the `overflow: hidden` is for on the original class). So we have an element that is 100% width, and then I also do a few hacks to make transitions think it has 100% height, and all animations will base themselves on that.

So the solution here would be to make the styles _only_ apply to top level `liquid-child`s, the ones we want to override with this.

**Comment by spencer516** [comment]
👍  — I'll take a stab at this right now and open a PR shortly.

**Comment by spencer516** [comment]
https://github.com/pzuraq/liquid-wormhole/pull/19

**Comment by svvitale** [comment]
I can confirm this corrected the issue in my example.  Thanks for taking the time to sort it out, @spencer516 !
