### ISSUE TITLE
default destination never removed

### ISSUE THREAD

**Issue by knownasilya** [pzuraq/liquid-wormhole#29]
The `.default-liquid-destination` element stays even after the item has disappeared. This "breaks the app" for users since it overlays everything and makes everything not clickable.

Basically, it looks like `removeDefaultDestination` is never called in the wormhole service.

I think #24 as a fix, exposed this bug.

----

Tested with the latest version, 2.0.4 and Ember 2.12.1

**Comment by pzuraq** [comment]
Looking into this today, so `removeDefaultDestination` is actually only supposed to be called when we teardown the app. The idea is that if there is no destination at all, we'll add it for you and remove it when the app is gone.

The `.default-liquid-destination` element itself should be an absolutely positioned element with `height: 0;` (implied, that's not actually in the styles) and `width: 100%`. This allows us to give the children an accurate width without having it interfere in the app, since it shouldn't actually overlay anything (because the height is `0`).

It sounds like you may have some styles that give it height by mistake? Either way, we should probably make the height explicit to prevent styling accidents like this in the future. I'd also like to stop relying on implicit styles entirely and start using `getBoundingClientRect` of the viewport, since that's what `liquid-wormhole` is generally being used for. Technically it can be used for anything right now though, so that might have to happen in v3.

**Comment by knownasilya** [comment]
Ok, that makes sense. I'm alright with a 3.0 👍

**Comment by pzuraq** [comment]
For now I'm going to set the height on the class, and suggest making sure the styling is correct. I'll be working on v3 sometime soon, but my backlog is pretty full at the moment so I'm not sure when that'll be. I'm also hoping to wait for `ember-animated` to land, since that would make it a lot easier to implement this in a less hack-y way. We'll see!
