### ISSUE TITLE
Liquid Wormhole destination '${destinationName}' already created

### ISSUE THREAD

**Issue by lovetingyuan** [pzuraq/liquid-wormhole#35]
```javascript
registerDestination(destinationName, destination) {
    if (this.destination.get(destinationName)) {
      throw new Error(`Liquid Wormhole destination '${destinationName}' already created`);
    }
    this.destination.set(destinationName, destination);
  },
```
why you throw an error? it does not make any sense, you can just ignore it

**Comment by pzuraq** [comment]
These are assertion errors, they tell us something is wrong because an invariant was invalidated. They're very common in Ember in general.

In this case, there can only be one liquid-destination component with a given name at a time. This is because liquid-wormholes warp themselves to a a destination by name - if two destinations exist with the same name, how would the wormhole know which one to use?

99% of use cases never actually require making your own liquid-destination, the service will generally manage it for you (I've never actually used it myself). It's a power user API, for someone who knows how it works and what it's doing and needs to do something very custom, and the assertions are there to help you understand how to use it (and not use it incorrectly).
