### ISSUE TITLE
Issue with liquid-destination

### ISSUE THREAD

**Issue by lovetingyuan** [pzuraq/liquid-wormhole#37]
fisrt, the liquid-destination will be destroied, and the destination list is empty, 
then the liquid-wormwhole will be destroied, but, but, you assert the destination list is not empty? wtf? 
then you throw an error,,,,,,,I don't know how you think this, but I hope you can fix it as soon as possible

**Comment by pzuraq** [comment]
This issue is not describing a bug or giving any useful information. The tests have been green on master, and the dummy app is working, which leads me to believe something with your implementation is broken or a bug has popped up in a new version of Ember or Liquid Fire.

Please:

1. Describe the bug in detail, with error codes and screen caps if possible.
2. Paste code snippets for how you've tried to use the library, especially if you have done anything strange or unusual with scheduling (sounds like a scheduling bug).
3. Post your Ember, Ember-CLI, and Liquid-Fire versions.

**Comment by pzuraq** [comment]
Also, in the future please don't make multiple issues for the same bug, and provide a descriptive title instead.

**Comment by pzuraq** [comment]
Closing this since you haven't responded. If you're still having issues feel free to reopen, I'm happy to work through any bugs or problems with the API.
